# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置  云服务器上
  # todo 需替换配置
  datasource:
    driver-class-name:
    url:
    username:
    password:
  redis:
    database:
    host:
    port:
    timeout:
    password:
  rabbitmq:
    host:
    port:
    username:
    password:

