# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置  云服务器上
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.95.77:3306/xiaocbi
    username: caodong
    password: 123456
  redis:
    database: 1
    host:  114.132.95.77
    port: 6379
    timeout: 5000
    password: 123456
  rabbitmq:
    host: 114.132.95.77
    port: 5672
    username: admin
    password: 123456

